# Generated by Django 4.2.23 on 2025-07-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('account', models.CharField(max_length=20, unique=True)),
                ('sort_code', models.CharField(max_length=8)),
                ('bank_name', models.CharField(max_length=100)),
            ],
        ),
    ]
