# Generated by Django 4.2.23 on 2025-07-10 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0003_remove_invoice_hours_remove_invoice_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
