# Generated by Django 4.2.23 on 2025-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0005_remove_invoice_created_at_invoice_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
