# Generated by Django 4.2.23 on 2025-07-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0007_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='color',
            field=models.CharField(default='#000000', help_text='選擇顏色 HEX 編碼', max_length=7),
        ),
        migrations.AddField(
            model_name='brand',
            name='coop_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='合作時數'),
        ),
        migrations.AddField(
            model_name='brand',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liveapp.person', verbose_name='負責人'),
        ),
    ]
