# Generated by Django 4.2.23 on 2025-07-17 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0008_brand_color_brand_coop_hours_brand_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='結束日期'),
        ),
        migrations.AddField(
            model_name='brand',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='開始日期'),
        ),
    ]
