# Generated by Django 4.2.23 on 2025-07-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0009_brand_end_date_brand_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liveapp.brand', verbose_name='品牌'),
        ),
    ]
