# Generated by Django 4.2.23 on 2025-07-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0010_schedule_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cancel_count',
            field=models.IntegerField(default=0, verbose_name='取消次數'),
        ),
        migrations.AddField(
            model_name='person',
            name='late_count',
            field=models.IntegerField(default=0, verbose_name='遲到次數'),
        ),
    ]
