# Generated by Django 4.2.23 on 2025-07-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0011_person_cancel_count_person_late_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_late_cancellation',
            field=models.BooleanField(default=False),
        ),
    ]
