# Generated by Django 4.2.23 on 2025-07-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0012_schedule_is_late_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='late_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
