# Generated by Django 4.2.23 on 2025-07-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0013_schedule_late_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
