# Generated by Django 4.2.23 on 2025-07-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0014_invoiceitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='暱稱'),
        ),
    ]
