# Generated by Django 4.2.23 on 2025-07-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0016_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Company'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='modification_reason',
            field=models.TextField(blank=True, verbose_name='修改原因'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='modification_status',
            field=models.CharField(choices=[('normal', '正常'), ('late', '遲到'), ('cancelled', '取消'), ('other', '其他')], default='normal', max_length=20, verbose_name='修改狀態'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修改時間'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='coop_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='合作時數(30天/單位)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
    ]
